import { Project, Task, Achievement } from '@/types'

export const seedProjects: Project[] = [
  {
    id: '1',
    name: 'LayerZero',
    slug: 'layerzero',
    description: 'Омничейн протокол для межсетевого взаимодействия',
    category: 'infra',
    ecosystem: 'multi-chain',
    funding_amount: 283000000,
    funding_currency: 'USD',
    investors: ['a16z', 'Sequoia', 'Coinbase Ventures', 'FT Ventures'],
    token_status: 'no_token',
    snapshot_status: 'upcoming',
    snapshot_date: '2025-06-01T00:00:00Z',
    estimated_reward_min: 3000,
    estimated_reward_max: 8000,
    farming_difficulty: 6,
    risk_score: 3,
    farming_cost: 100,
    probability_score: 92,
    deadline: null,
    website_url: 'https://layerzero.network',
    twitter_url: 'https://twitter.com/LayerZero_Labs',
    discord_url: 'https://discord.gg/layerzero',
    telegram_url: null,
    docs_url: 'https://layerzero.network/docs',
    github_url: 'https://github.com/LayerZero-Labs',
    ai_summary: 'LayerZero — омничейн-протокол с сильным бэкраундом. Токен не запущен. Высокая вероятность ретроактивного аирдропа для активных пользователей мостов и стейкинга.',
    status: 'active',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2025-05-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'zkSync',
    slug: 'zksync',
    description: 'ZK-rollup Layer 2 решение для Ethereum',
    category: 'layer2',
    ecosystem: 'ethereum',
    funding_amount: 458000000,
    funding_currency: 'USD',
    investors: ['a16z', 'Blockchain Capital', 'Dragonfly'],
    token_status: 'announced',
    snapshot_status: 'active',
    snapshot_date: '2025-05-19T00:00:00Z',
    estimated_reward_min: 2000,
    estimated_reward_max: 5000,
    farming_difficulty: 5,
    risk_score: 2,
    farming_cost: 50,
    probability_score: 88,
    deadline: '2025-05-19T00:00:00Z',
    website_url: 'https://zksync.io',
    twitter_url: 'https://twitter.com/zksync',
    discord_url: 'https://discord.gg/zksync',
    telegram_url: null,
    docs_url: 'https://docs.zksync.io',
    github_url: 'https://github.com/matter-labs',
    ai_summary: 'zkSync — лидер ZK-rollup. Snapshot активен. Осталось 2 дня. Рекомендуется выполнить минимум 2 транзакции для повышения элиджиблити.',
    status: 'active',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2025-05-15T00:00:00Z',
  },
  {
    id: '3',
    name: 'Scroll',
    slug: 'scroll',
    description: 'zkEVM Layer 2 с нативной совместимостью',
    category: 'layer2',
    ecosystem: 'ethereum',
    funding_amount: 80000000,
    funding_currency: 'USD',
    investors: ['Polychain', 'Bain Capital Crypto', 'Robot Ventures'],
    token_status: 'no_token',
    snapshot_status: 'unknown',
    snapshot_date: null,
    estimated_reward_min: 1500,
    estimated_reward_max: 4000,
    farming_difficulty: 5,
    risk_score: 4,
    farming_cost: 30,
    probability_score: 87,
    deadline: null,
    website_url: 'https://scroll.io',
    twitter_url: 'https://twitter.com/Scroll_ZKP',
    discord_url: 'https://discord.gg/scroll',
    telegram_url: null,
    docs_url: 'https://docs.scroll.io',
    github_url: 'https://github.com/scroll-tech',
    ai_summary: 'Scroll — zkEVM L2 с $80M funding. Токен не запущен. Активный тестнет. Ранние пользователи могут получить бонусы.',
    status: 'active',
    created_at: '2024-02-01T00:00:00Z',
    updated_at: '2025-05-10T00:00:00Z',
  },
  {
    id: '4',
    name: 'StarkNet',
    slug: 'starknet',
    description: 'Валидити роллап (ZK-rollup) Layer 2',
    category: 'layer2',
    ecosystem: 'ethereum',
    funding_amount: 270000000,
    funding_currency: 'USD',
    investors: ['Sequoia', 'Paradigm', 'Tiger Global'],
    token_status: 'launched',
    snapshot_status: 'passed',
    snapshot_date: '2024-11-01T00:00:00Z',
    estimated_reward_min: 1000,
    estimated_reward_max: 3000,
    farming_difficulty: 7,
    risk_score: 3,
    farming_cost: 80,
    probability_score: 78,
    deadline: null,
    website_url: 'https://starknet.io',
    twitter_url: 'https://twitter.com/StarkNetEco',
    discord_url: 'https://discord.gg/starknet',
    telegram_url: null,
    docs_url: 'https://docs.starknet.io',
    github_url: 'https://github.com/starkware-libs',
    ai_summary: 'StarkNet — ZK-rollup от StarkWare. Токен STRK уже запущен. Возможен второй раунд аирдропа для новых активных пользователей.',
    status: 'active',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2025-05-01T00:00:00Z',
  },
  {
    id: '5',
    name: 'Monad',
    slug: 'monad',
    description: 'Высокопроизводительный EVM-совместимый L1',
    category: 'layer1',
    ecosystem: 'ethereum',
    funding_amount: 225000000,
    funding_currency: 'USD',
    investors: ['Paradigm', 'Coinbase Ventures', 'Dragonfly'],
    token_status: 'no_token',
    snapshot_status: 'unknown',
    snapshot_date: null,
    estimated_reward_min: 1500,
    estimated_reward_max: 4000,
    farming_difficulty: 5,
    risk_score: 5,
    farming_cost: 20,
    probability_score: 78,
    deadline: null,
    website_url: 'https://monad.xyz',
    twitter_url: 'https://twitter.com/monad_xyz',
    discord_url: 'https://discord.gg/monad',
    telegram_url: null,
    docs_url: 'https://docs.monad.xyz',
    github_url: null,
    ai_summary: 'Monad — новый L1 с $225M funding от Paradigm. Тестнет активен. Ранние пользователи получат бонусы.',
    status: 'active',
    created_at: '2024-03-01T00:00:00Z',
    updated_at: '2025-05-12T00:00:00Z',
  },
  {
    id: '6',
    name: 'Berachain',
    slug: 'berachain',
    description: 'EVM-совместимый L1 с Proof-of-Liquidity',
    category: 'layer1',
    ecosystem: 'cosmos',
    funding_amount: 100000000,
    funding_currency: 'USD',
    investors: ['Hack VC', 'Polychain', 'Robot Ventures'],
    token_status: 'no_token',
    snapshot_status: 'unknown',
    snapshot_date: null,
    estimated_reward_min: 800,
    estimated_reward_max: 2500,
    farming_difficulty: 4,
    risk_score: 5,
    farming_cost: 0,
    probability_score: 72,
    deadline: null,
    website_url: 'https://berachain.com',
    twitter_url: 'https://twitter.com/berachain',
    discord_url: 'https://discord.gg/berachain',
    telegram_url: null,
    docs_url: 'https://docs.berachain.com',
    github_url: 'https://github.com/berachain',
    ai_summary: 'Berachain — L1 с уникальным Proof-of-Liquidity. Бесплатный тестнет. Социальные квесты активны.',
    status: 'active',
    created_at: '2024-04-01T00:00:00Z',
    updated_at: '2025-05-08T00:00:00Z',
  },
  {
    id: '7',
    name: 'EigenLayer',
    slug: 'eigenlayer',
    description: 'Протокол рестейкинга для Ethereum',
    category: 'defi',
    ecosystem: 'ethereum',
    funding_amount: 145000000,
    funding_currency: 'USD',
    investors: ['Blockchain Capital', 'Paradigm', 'Coinbase Ventures'],
    token_status: 'launched',
    snapshot_status: 'passed',
    snapshot_date: '2024-06-01T00:00:00Z',
    estimated_reward_min: 2000,
    estimated_reward_max: 6000,
    farming_difficulty: 8,
    risk_score: 4,
    farming_cost: 500,
    probability_score: 65,
    deadline: null,
    website_url: 'https://eigenlayer.xyz',
    twitter_url: 'https://twitter.com/eigenlayer',
    discord_url: 'https://discord.gg/eigenlayer',
    telegram_url: null,
    docs_url: 'https://docs.eigenlayer.xyz',
    github_url: 'https://github.com/Layr-Labs',
    ai_summary: 'EigenLayer — протокол рестейкинга. Токен EIGEN запущен. Возможен второй раунд для новых рестейкеров.',
    status: 'active',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2025-05-01T00:00:00Z',
  },
  {
    id: '8',
    name: 'Hyperlane',
    slug: 'hyperlane',
    description: 'Permissionless протокол межсетевого взаимодействия',
    category: 'infra',
    ecosystem: 'multi-chain',
    funding_amount: 55000000,
    funding_currency: 'USD',
    investors: ['Coinbase Ventures', 'Bain Capital Crypto', 'Robot Ventures'],
    token_status: 'no_token',
    snapshot_status: 'unknown',
    snapshot_date: null,
    estimated_reward_min: 1000,
    estimated_reward_max: 3000,
    farming_difficulty: 4,
    risk_score: 5,
    farming_cost: 15,
    probability_score: 70,
    deadline: null,
    website_url: 'https://hyperlane.xyz',
    twitter_url: 'https://twitter.com/Hyperlane_xyz',
    discord_url: 'https://discord.gg/hyperlane',
    telegram_url: null,
    docs_url: 'https://docs.hyperlane.xyz',
    github_url: 'https://github.com/hyperlane-xyz',
    ai_summary: 'Hyperlane — permissionless interoperability. Токен не запущен. Активная экосистема с растущим TVL.',
    status: 'active',
    created_at: '2024-05-01T00:00:00Z',
    updated_at: '2025-05-14T00:00:00Z',
  },
]

export const seedTasks: Task[] = [
  { id: '1', project_id: '1', title: 'Бридж ETH через Stargate', description: 'Бридж минимум 0.1 ETH', task_type: 'bridge', requirement_type: 'tx_count', target_value: 1, target_unit: 'transactions', deadline: null, is_recurring: false, recurrence_interval: null, difficulty: 3, estimated_time_minutes: 15, created_at: '2024-01-01T00:00:00Z' },
  { id: '2', project_id: '1', title: 'Свап на SushiSwap', description: 'Выполнить минимум 1 свап', task_type: 'swap', requirement_type: 'tx_count', target_value: 1, target_unit: 'transactions', deadline: null, is_recurring: false, recurrence_interval: null, difficulty: 2, estimated_time_minutes: 10, created_at: '2024-01-01T00:00:00Z' },
  { id: '3', project_id: '1', title: 'Стейк STG токенов', description: 'Застейкать STG токены', task_type: 'stake', requirement_type: 'tx_count', target_value: 1, target_unit: 'transactions', deadline: null, is_recurring: false, recurrence_interval: null, difficulty: 3, estimated_time_minutes: 10, created_at: '2024-01-01T00:00:00Z' },
  { id: '4', project_id: '1', title: 'Зайти в Discord + роль', description: 'Присоединиться и верифицироваться', task_type: 'discord', requirement_type: 'role', target_value: 1, target_unit: 'boolean', deadline: null, is_recurring: false, recurrence_interval: null, difficulty: 1, estimated_time_minutes: 5, created_at: '2024-01-01T00:00:00Z' },
  { id: '5', project_id: '1', title: '5 бридж транзакций', description: 'Бридж активов минимум 5 раз', task_type: 'bridge', requirement_type: 'tx_count', target_value: 5, target_unit: 'transactions', deadline: null, is_recurring: false, recurrence_interval: null, difficulty: 5, estimated_time_minutes: 60, created_at: '2024-01-01T00:00:00Z' },
  { id: '6', project_id: '2', title: 'Бридж на zkSync Era', description: 'Бридж ETH на zkSync Era', task_type: 'bridge', requirement_type: 'tx_count', target_value: 1, target_unit: 'transactions', deadline: '2025-05-19T00:00:00Z', is_recurring: false, recurrence_interval: null, difficulty: 3, estimated_time_minutes: 15, created_at: '2024-01-01T00:00:00Z' },
  { id: '7', project_id: '2', title: 'Свап на SyncSwap', description: 'Свап на SyncSwap DEX', task_type: 'swap', requirement_type: 'tx_count', target_value: 1, target_unit: 'transactions', deadline: '2025-05-19T00:00:00Z', is_recurring: false, recurrence_interval: null, difficulty: 2, estimated_time_minutes: 10, created_at: '2024-01-01T00:00:00Z' },
  { id: '8', project_id: '2', title: 'Предоставить ликвидность', description: 'Добавить ликвидность в пул', task_type: 'stake', requirement_type: 'volume', target_value: 100, target_unit: 'usd', deadline: '2025-05-19T00:00:00Z', is_recurring: false, recurrence_interval: null, difficulty: 4, estimated_time_minutes: 20, created_at: '2024-01-01T00:00:00Z' },
  { id: '9', project_id: '3', title: 'Бридж на Scroll', description: 'Бридж ETH на Scroll', task_type: 'bridge', requirement_type: 'tx_count', target_value: 1, target_unit: 'transactions', deadline: null, is_recurring: false, recurrence_interval: null, difficulty: 3, estimated_time_minutes: 15, created_at: '2024-02-01T00:00:00Z' },
  { id: '10', project_id: '3', title: '3 свапа на Scroll DEX', description: 'Минимум 3 свапа', task_type: 'swap', requirement_type: 'tx_count', target_value: 3, target_unit: 'transactions', deadline: null, is_recurring: false, recurrence_interval: null, difficulty: 3, estimated_time_minutes: 30, created_at: '2024-02-01T00:00:00Z' },
  { id: '11', project_id: '5', title: 'Зайти в Monad тестнет', description: 'Участвовать в тестнете', task_type: 'testnet', requirement_type: 'tx_count', target_value: 1, target_unit: 'transactions', deadline: null, is_recurring: false, recurrence_interval: null, difficulty: 2, estimated_time_minutes: 20, created_at: '2024-03-01T00:00:00Z' },
  { id: '12', project_id: '5', title: 'Galxe квесты', description: 'Социальные квесты на Galxe', task_type: 'social', requirement_type: 'quest', target_value: 5, target_unit: 'quests', deadline: null, is_recurring: false, recurrence_interval: null, difficulty: 2, estimated_time_minutes: 30, created_at: '2024-03-01T00:00:00Z' },
  { id: '13', project_id: '6', title: 'Berachain тестнет', description: 'Участвовать в bArtio тестнете', task_type: 'testnet', requirement_type: 'tx_count', target_value: 1, target_unit: 'transactions', deadline: null, is_recurring: false, recurrence_interval: null, difficulty: 1, estimated_time_minutes: 15, created_at: '2024-04-01T00:00:00Z' },
  { id: '14', project_id: '6', title: 'Социальные квесты', description: 'Twitter, Discord, Zealy', task_type: 'social', requirement_type: 'quest', target_value: 3, target_unit: 'quests', deadline: null, is_recurring: false, recurrence_interval: null, difficulty: 1, estimated_time_minutes: 20, created_at: '2024-04-01T00:00:00Z' },
]

export const seedAchievements: Achievement[] = [
  { id: '1', slug: 'first-blood', name: 'Первая кровь', description: 'Завершил первый проект', icon: '🥇', rarity: 'common', xp_reward: 50, criteria: { type: 'projects_completed', value: 1 }, created_at: '2024-01-01T00:00:00Z' },
  { id: '2', slug: 'task-master', name: 'Мастер задач', description: 'Выполнил 100 задач', icon: '🥈', rarity: 'uncommon', xp_reward: 200, criteria: { type: 'tasks_done', value: 100 }, created_at: '2024-01-01T00:00:00Z' },
  { id: '3', slug: 'whale', name: 'Кит', description: 'Портфель $10K+', icon: '🥉', rarity: 'rare', xp_reward: 500, criteria: { type: 'portfolio_value', value: 10000 }, created_at: '2024-01-01T00:00:00Z' },
  { id: '4', slug: 'streak-lord', name: 'Повелитель стриков', description: '30 дней стрик', icon: '🔥', rarity: 'uncommon', xp_reward: 300, criteria: { type: 'streak_days', value: 30 }, created_at: '2024-01-01T00:00:00Z' },
  { id: '5', slug: 'sniper', name: 'Снайпер', description: '90%+ завершение на 5 проектах', icon: '🎯', rarity: 'rare', xp_reward: 400, criteria: { type: 'high_completion_projects', value: 5 }, created_at: '2024-01-01T00:00:00Z' },
  { id: '6', slug: 'diamond-hands', name: 'Алмазные руки', description: 'Отслеживал проект 180+ дней', icon: '💎', rarity: 'epic', xp_reward: 600, criteria: { type: 'tracking_days', value: 180 }, created_at: '2024-01-01T00:00:00Z' },
  { id: '7', slug: 'ai-whisperer', name: 'Шептатель ИИ', description: 'Использовал ИИ парсер 25 раз', icon: '🧠', rarity: 'uncommon', xp_reward: 250, criteria: { type: 'ai_uses', value: 25 }, created_at: '2024-01-01T00:00:00Z' },
  { id: '8', slug: 'multi-chain', name: 'Мультичейн', description: 'Активен на 5+ сетях', icon: '🌐', rarity: 'rare', xp_reward: 350, criteria: { type: 'chains_active', value: 5 }, created_at: '2024-01-01T00:00:00Z' },
]

export const seedReminders = [
  {
    id: '1',
    title: 'Снимок zkSync',
    message: 'Выполните ещё 2 транзакции до снимка',
    type: 'snapshot' as const,
    scheduled_at: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    project: { name: 'zkSync' },
    channel: 'in_app',
    sent_at: null,
  },
  {
    id: '2',
    title: 'LayerZero Раунд 3',
    message: 'Дедлайн бриджа приближается',
    type: 'deadline' as const,
    scheduled_at: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    project: { name: 'LayerZero' },
    channel: 'in_app',
    sent_at: null,
  },
  {
    id: '3',
    title: 'Ежедневные задачи',
    message: 'Выполнить ежедневный свап на Scroll',
    type: 'activity' as const,
    scheduled_at: new Date(Date.now() + 12 * 60 * 60 * 1000).toISOString(),
    project: { name: 'Scroll' },
    channel: 'in_app',
    sent_at: null,
  },
]

export const seedWallets = [
  {
    id: '1',
    address: '0xabc123def456789abc123def456789abc123def2',
    label: 'Основной',
    tags: ['airdrop', 'defi'],
    chain: 'ethereum',
    projects: 12,
    completed: 4,
    eligibility: [
      { project: 'LayerZero', score: 85 },
      { project: 'zkSync', score: 72 },
      { project: 'Scroll', score: 45 },
    ],
  },
  {
    id: '2',
    address: '0x789fabc3def456789abc123def456789abc123',
    label: 'DeFi',
    tags: ['defi'],
    chain: 'ethereum',
    projects: 5,
    completed: 1,
    eligibility: [
      { project: 'EigenLayer', score: 68 },
      { project: 'Lido', score: 55 },
    ],
  },
]
